import os
import time

import requests

# urls from http://spendingstories.org/api/themes/
assets = [
    "/themes/admin-culture.svg",
    "/themes/admin-order-safety.svg",
    "/themes/aid.svg",
    "/themes/aid-developing-countries.svg",
    "/themes/airplane.svg",
    "/themes/ambulance.svg",
    "/themes/books.svg",
    "/themes/car.svg",
    "/themes/civil-defence.svg",
    "/themes/civilian-action.svg",
    "/themes/coal.svg",
    "/themes/communication.svg",
    "/themes/community.svg",
    "/themes/construction.svg",
    "/themes/courts.svg",
    "/themes/culture.svg",
    "/themes/defence.svg",
    "/themes/defence-admin.svg",
    "/themes/defence-research.svg",
    "/themes/dollar.svg",
    "/themes/economic-aid.svg",
    "/themes/economy-tourism.svg",
    "/themes/education.svg",
    "/themes/electricity.svg",
    "/themes/energy.svg",
    "/themes/environment.svg",
    "/themes/environment-admin.svg",
    "/themes/euro.svg",
    "/themes/family.svg",
    "/themes/farms.svg",
    "/themes/financial-admin.svg",
    "/themes/fishing.svg",
    "/themes/foreign-military-aid.svg",
    "/themes/forest.svg",
    "/themes/fuel.svg",
    "/themes/garbage.svg",
    "/themes/government.svg",
    "/themes/health.svg",
    "/themes/helping-others.svg",
    "/themes/hospital.svg",
    "/themes/hospital-specialized.svg",
    "/themes/housing.svg",
    "/themes/human-resources.svg",
    "/themes/labour.svg",
    "/themes/legislative.svg",
    "/themes/manufactoring-construction.svg",
    "/themes/media.svg",
    "/themes/medical-supplies.svg",
    "/themes/military.svg",
    "/themes/misc-services.svg",
    "/themes/money.svg",
    "/themes/nuclear.svg",
    "/themes/old-age.svg",
    "/themes/order-safety.svg",
    "/themes/other-medical.svg",
    "/themes/our-streets.svg",
    "/themes/petrol.svg",
    "/themes/police2.svg",
    "/themes/pollution.svg",
    "/themes/post-secondary.svg",
    "/themes/pound2.svg",
    "/themes/pre-school.svg",
    "/themes/primary.svg",
    "/themes/prisons.svg",
    "/themes/publicaffairs.svg",
    "/themes/public-debt.svg",
    "/themes/railways.svg",
    "/themes/rd-order-safety.svg",
    "/themes/research.svg",
    "/themes/satellite-dish.svg",
    "/themes/schools.svg",
    "/themes/secondary-lower.svg",
    "/themes/secondary-upper.svg",
    "/themes/social-systems.svg",
    "/themes/sports.svg",
    "/themes/street-lights.svg",
    "/themes/traffic-watersup.svg",
    "/themes/transport.svg",
    "/themes/tree.svg",
    "/themes/unemployment.svg",
    "/themes/unknown.svg",
    "/themes/waste.svg",
    "/themes/water.svg",
    "/themes/wheelchair.svg",
    "/themes/wind.svg",
]

for asset in assets:
    print(f"Getting {asset} ...")
    r = requests.get(asset)
    _, tail = os.path.split(asset)
    filepath = "..themes/" + tail
    with open(filepath, "wb") as f:
        f.write(r.content)
    time.sleep(0.2)  # let's not be too aggressive with requests
